exp_name: "ACT-Maniskill"

# ==========> 环境信息
envs:
  env_id: "MovePlate"

# ==========> 模型信息
chunk_size: 50
scale: 150  # 每条轨迹中采样的数据样本条数
train_split: 0.8  # 训/验比是 8:2 且直接在仿真环境中部署做测试
d_model: 512
d_proprioception: ???
d_action: ???
d_z_distribution: 32
d_feedforward: 2048
n_head: 8
n_representation_encoder_layers: 3
n_encoder_layers: 3
n_decoder_layers: 6
dropout: 0.1
activation: "relu"
normalize_before: false

# ==========> 视觉骨干
resnet_name: resnet18
return_interm_layers: false

# ==========> 训练和评估
seed: 42  # 随机数种子
torch_deterministic: true
cuda: true
batch_size: 64
total_iters: 50000  # 每一个 iter 从数据集中获得一个 batch 信息, 做一次梯度下降
eval_frequency: 1000  # 进行验证集测试的频率
test_frequency: 1000  # 把模型放到仿真环境的评估的频率
save_frequency: 1000  # 模型保存的频率
num_eval_episodes: 10  # 仿真器中每个并行环境跑了多少 episodes
capture_video: false #录制视频
video_path: "./videos/bigym/MovePlate"
lr: 0.0001  # 模型的学习率
lr_backbone: 0.00001  # 视觉骨干模型的全参微调学习率
weight_decay: 0.0001  # 权重衰减
kl_weight: 1  # kl 散度做梯度下降的优先级
render: false  # 是否在测试时候进行渲染

# ==========> 训练记录器
wandb:
  need: true
  project_name: "New-ACT-Bigym"

# ==========> 其他一些参数
include_depth: false

